<a href="https://colab.research.google.com/github/sam69387/gensim/blob/develop/pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DMA: PANDAS TUTORIAL**

In [0]:
import pandas as pd

#### Creating a new dataframe

In [0]:
# Dataframe from a dictionary
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'population': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data)

# Dataframe from a list
#df = pd.DataFrame([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]], columns=["col1", "col2", "col3", "col4"])

In [0]:
#type(df)
#type(data)
df.head()

   population   state  year
0         1.5    Ohio  2000
1         1.7    Ohio  2001
2         3.6    Ohio  2002
3         2.4  Nevada  2001
4         2.9  Nevada  2002

#### Understanding your dataframe

In [0]:
df.shape
df.columns

Index([u'population', u'state', u'year'], dtype='object')

#### Accessing Columns

In [0]:
df['state']
df.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

#### A quick statistical profile of all the numeric columns

In [0]:
df.describe()

       population        year
count    5.000000     5.00000
mean     2.420000  2001.20000
std      0.864292     0.83666
min      1.500000  2000.00000
25%      1.700000  2001.00000
50%      2.400000  2001.00000
75%      2.900000  2002.00000
max      3.600000  2002.00000

#### Profile of a column

In [0]:
df['population'].describe()

count    5.000000
mean     2.420000
std      0.864292
min      1.500000
25%      1.700000
50%      2.400000
75%      2.900000
max      3.600000
Name: population, dtype: float64

#### Can we get the profile of a column that is not numeric, like state?

In [0]:
df['state'].describe()

### Slicing

In [0]:
#Get the first 3 rows of df
df[:3]

   population state  year
0         1.5  Ohio  2000
1         1.7  Ohio  2001
2         3.6  Ohio  2002

#### Can we get a specific row of the dataframe?

In [0]:
df[1:2]

   population state  year
1         1.7  Ohio  2001

#### loc and iloc

In [0]:
df.loc[1]
df.iloc[1]

population     1.7
state         Ohio
year          2001
Name: 1, dtype: object

#### The difference between regular slicing and loc/iloc shows when you wish to access individual cells.

In [0]:
df.loc[1:2]

df.iloc[1,2]

#df.loc[:3]

2001

#### With the magic of loc/iloc, slicing can work for both rows and colums

In [0]:
df.loc[:3, :'state']

#df.iloc[:3,:2]

   population   state
0         1.5    Ohio
1         1.7    Ohio
2         3.6    Ohio
3         2.4  Nevada

### Now what if you wish to import a csv file instead of creating one?

In [0]:
!wget http://people.ischool.berkeley.edu/~zp/course_datasets/yelp_reviews.csv
#!unzip yelp_reviews.zip
print('Dataset Downloaded: yelp_reviews.csv')
df=pd.read_csv('yelp_reviews.csv')
print(df.head())

--2019-01-31 06:54:35--  http://people.ischool.berkeley.edu/~zp/course_datasets/yelp_reviews.csv
Resolving people.ischool.berkeley.edu (people.ischool.berkeley.edu)... 128.32.78.16
Connecting to people.ischool.berkeley.edu (people.ischool.berkeley.edu)|128.32.78.16|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 376638166 (359M) [text/csv]
Saving to: ‘yelp_reviews.csv’

yelp_reviews.csv    100%[===================>] 359.19M  8.28MB/s    in 2m 1s

2019-01-31 06:56:37 (2.97 MB/s) - ‘yelp_reviews.csv’ saved [376638166/376638166]

Dataset Downloaded: yelp_reviews.csv
     type             business_id                 user_id  stars  \
0  review  mxrXVZWc6PWk81gvOVNOUw  mv7shusL4Xb6TylVYBv4CA      4
1  review  mxrXVZWc6PWk81gvOVNOUw  0aN5QPhs-VwK2vusKG0waQ      5
2  review  kK4AzZ0YWI-U2G-paAL7Fg  0aN5QPhs-VwK2vusKG0waQ      5
3  review  mxrXVZWc6PWk81gvOVNOUw  1JUwyYab-uJzEx_FRd81Zg      5
4  review  mxrXVZWc6PWk81gvOVNOUw  2Zd3Xy8hUVmZkNg7RyNjhg      4

                                                text        date  cool_votes  \
0  Definitely try the duck dish.   I rank it amon...  2011-06-13           0
1  Big Ass Burger was awesome! Great $5 mojitos. ...  2011-06-25           1
2             Unbelievable sandwiches! Good service.  2011-06-25           0
3  Awesome, awesome, awesome! My mom and sister a...  2011-07-18           1
4  I had the ribs they were great.  The beer sele...  2011-07-19           1

   useful_votes  funny_votes
0             0            0
1             0            0
2             0            0
3             1            0
4             0            1

In [0]:
df.head()

,type,business_id,user_id,stars,text,date,cool_votes,useful_votes,funny_votes
0,review,mxrXVZWc6PWk81gvOVNOUw,mv7shusL4Xb6TylVYBv4CA,4,Definitely try the duck dish. I rank it amon...,2011-06-13,0,0,0
1,review,mxrXVZWc6PWk81gvOVNOUw,0aN5QPhs-VwK2vusKG0waQ,5,Big Ass Burger was awesome! Great $5 mojitos. ...,2011-06-25,1,0,0
2,review,kK4AzZ0YWI-U2G-paAL7Fg,0aN5QPhs-VwK2vusKG0waQ,5,Unbelievable sandwiches! Good service.,2011-06-25,0,0,0
3,review,mxrXVZWc6PWk81gvOVNOUw,1JUwyYab-uJzEx_FRd81Zg,5,"Awesome, awesome, awesome! My mom and sister a...",2011-07-18,1,1,0
4,review,mxrXVZWc6PWk81gvOVNOUw,2Zd3Xy8hUVmZkNg7RyNjhg,4,I had the ribs they were great. The beer sele...,2011-07-19,1,0,1

#### Slicing

In [0]:
#Slicing

df[:500]

#Slicing a column

df['cool_votes'][:500]

0      0
1      1
2      0
3      1
4      1
5      0
6      0
7      0
8      1
9      0
10     0
11     0
12     0
13     1
14     0
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     0
23     1
24     0
25     0
26     0
27     0
28     0
29     0
      ..
470    0
471    0
472    2
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    1
493    0
494    0
495    0
496    0
497    0
498    0
499    0
Name: cool_votes, Length: 500, dtype: int64

### Filtering a dataset based on column values

In [0]:
df_uncool = df[df['cool_votes']==0]

df_uncool.head()
#Filter a subset based on column values 
df[:1500][df['cool_votes']==0]

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """

,type,business_id,user_id,stars,text,date,cool_votes,useful_votes,funny_votes
0,review,mxrXVZWc6PWk81gvOVNOUw,mv7shusL4Xb6TylVYBv4CA,4,Definitely try the duck dish. I rank it amon...,2011-06-13,0,0,0
2,review,kK4AzZ0YWI-U2G-paAL7Fg,0aN5QPhs-VwK2vusKG0waQ,5,Unbelievable sandwiches! Good service.,2011-06-25,0,0,0
5,review,iDYzGVIF1TDWdjHNgNjCVw,2Zd3Xy8hUVmZkNg7RyNjhg,4,"Great food, great drink. I had the crab enchil...",2011-07-19,0,0,0
6,review,dsMvINhoQbIQgSRTBv2B6g,2Zd3Xy8hUVmZkNg7RyNjhg,3,The only thing keeping this 5 stars is the pri...,2012-10-07,0,2,0
7,review,ZXRcWs5SUCvSfb8I2aLOnA,2Zd3Xy8hUVmZkNg7RyNjhg,4,My wife and I have been to many different Spas...,2010-08-24,0,0,0
9,review,GGVcdnKoRXldVEgergSF-A,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good lunch place. Everything I have had is be...,2012-11-17,0,0,0
10,review,1Q_H3BLhKBymF6Se8FfZNw,2Zd3Xy8hUVmZkNg7RyNjhg,3,When you look at the price you pay you expect ...,2010-08-24,0,0,0
11,review,YKOvlBNkF4KpUP9q7x862w,2Zd3Xy8hUVmZkNg7RyNjhg,3,"Very nice restaurant, great food, great servic...",2015-08-24,0,0,0
12,review,YYy3aQoLvjLhXPkpB32uzA,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food and service are OK. I will go back. ...,2014-04-22,0,0,0
14,review,sjCRI-lCh4KLO_RYQdlEeQ,2Zd3Xy8hUVmZkNg7RyNjhg,1,I went here with Friends last Friday. All my ...,2011-06-27,0,5,1
15,review,nMHhuYan8e3cONo3PornJA,2Zd3Xy8hUVmZkNg7RyNjhg,5,"This is a unique, awesome place with a cool me...",2011-07-19,0,0,0
17,review,jtzhY-P4H6WSYpv5rWhxtw,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food was great the service was bad. If th...,2014-04-22,0,1,0
18,review,Cr2JNnewX53TYd9w6qw6Jw,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good burger good value.,2011-07-26,0,1,0
19,review,GDmue1oJaem9ilywDtA4_A,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was great. The service was so-so. A...,2013-02-14,0,0,0
20,review,JjLy3f1LyaE9ayRK18XQRg,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was very good. Great flavor not just...,2016-02-11,0,0,0
21,review,mxrXVZWc6PWk81gvOVNOUw,fuGfZWfDFf97d6UyuO3d8w,4,I was in Scottsdale on business and this was a...,2011-09-27,0,0,0
22,review,E7nk0lC317pGxMX56gvaVQ,fuGfZWfDFf97d6UyuO3d8w,2,First off to call yourself a bar and not serve...,2011-09-27,0,2,0
24,review,IwShjaQLAvqV2msU4bh3ww,fuGfZWfDFf97d6UyuO3d8w,5,"This place is a Gem! It's small, dont get me w...",2013-11-28,0,0,0
25,review,mxrXVZWc6PWk81gvOVNOUw,ghvcceMVfgukJMVsi9A1bA,4,Fresh Baked Bread to start!\nGreat Tortilla So...,2011-10-02,0,1,0
26,review,UKgSs_SJzW9fu4CwhIV1yA,ghvcceMVfgukJMVsi9A1bA,5,The only thing that comes to my mind is why ar...,2011-10-02,0,1,0
27,review,On_3zLdujQdvDbBYUirNWw,ghvcceMVfgukJMVsi9A1bA,3,Service was 4 stars but we're here for the foo...,2011-10-02,0,0,0
28,review,OE5nAmaSVaopeRS1Cs9Kuw,ghvcceMVfgukJMVsi9A1bA,3,LISTEN CLOSELY FELLOW YELPERS.....\n\nTHIS 3 S...,2011-10-02,0,0,0
29,review,mxrXVZWc6PWk81gvOVNOUw,66aU_4HfubG5wJ3ZPR29og,4,"My friends wanted to eat ""Southwest cuisine,"" ...",2011-10-28,0,0,0
31,review,mxrXVZWc6PWk81gvOVNOUw,fRxsxrX71_qMpeF2MFJcYw,4,Great grub. The green chili pork appetizer is ...,2011-12-26,0,1,0
32,review,Q4ULAiIE2qCA4RYplCTrUQ,fRxsxrX71_qMpeF2MFJcYw,1,Ferguson joined me on a business trip here and...,2013-05-11,0,5,0
33,review,NGJDjdiDJHmN2xxU7KauuA,fRxsxrX71_qMpeF2MFJcYw,2,"Quite a turd, actually. I've stayed at simila...",2015-02-04,0,0,0
34,review,BPi1Q5wX0_o5VlO_XRyYuQ,fRxsxrX71_qMpeF2MFJcYw,4,Always a great dinner experience at Bianco. I...,2016-02-27,0,0,0
35,review,mxrXVZWc6PWk81gvOVNOUw,wigVZqPYrWbz8ry_OlZADQ,3,"Food was good, but not great. Service was fan...",2012-01-03,0,0,0
36,review,iDYzGVIF1TDWdjHNgNjCVw,wigVZqPYrWbz8ry_OlZADQ,5,"Great margaritas, gauc, queso, and tacos. We w...",2012-01-03,0,0,0
37,review,hh2lP4_2N-tk_OxmaTf_qA,wigVZqPYrWbz8ry_OlZADQ,3,"Food was great, but the service was terrible. ...",2012-01-03,0,0,0
...,...,...,...,...,...,...,...,...,...
1456,review,4A628qyYpA4EhN6w6o-MYQ,5VrXpcPextrK7xgWwMpJyA,2,I wish I could leave more stars. I just can't...,2016-03-10,0,0,0
1457,review,h7CQfQkOf53nMMmlLJ3cRw,5VrXpcPextrK7xgWwMpJyA,2,I can't say that the owners aren't absolute di...,2015-09-19,0,1,0
1458,review,WBK5EJ73mmfGEW9DolBtBA,5VrXpcPextrK7xgWwMpJyA,5,Took me forever to write this review but this ...,2016-03-10,0,0,0
1461,review,UMoPsLLNET13dwLK85wI3A,5VrXpcPextrK7xgWwMpJyA,2,I have had my haircut here once before. Above...,2015-11-08,0,4,1
1462,review,cWs7rwDCUhCdXWZeRdKFzQ,5VrXpcPextrK7xgWwMpJyA,5,Martin talked me through every piece of pool a...,2016-03-02,0,0,0
1463,review,T7MTQix5KqdYb-4llIHfaw,5VrXpcPextrK7xgWwMpJyA,1,Failure from second 1. Phones don't work. H...,2016-06-27,0,0,0
1464,review,__V-dYRsH4cmt7ynZ3ulxQ,5VrXpcPextrK7xgWwMpJyA,5,Tyler has exceeded my expectations. Besides r...,2016-07-17,0,0,0
1465,review,4A628qyYpA4EhN6w6o-MYQ,MibHji0QCYlLsewuqq4wwA,3,"Food was good, pizza sauce was little bit swee...",2016-03-13,0,0,0
1466,review,kFVapB4z_5VoOnYazF_ERA,MibHji0QCYlLsewuqq4wwA,4,"Food was amazing. We ordered pizza, cheese br...",2016-05-27,0,0,0
1467,review,EGiGWZp_zSqdeftiFQ7MbA,MibHji0QCYlLsewuqq4wwA,5,This place is amazing! Everything taste fresh ...,2016-03-13,0,0,0
1468,review,v7OwbHgNgy_VQ9eP5FjvUA,MibHji0QCYlLsewuqq4wwA,1,not worth the wait to get in here. Service was...,2016-03-13,0,0,0
1469,review,aLMStInNBczJKtIJFMlwJA,MibHji0QCYlLsewuqq4wwA,1,Place is extremely loud regardless if you eat ...,2016-04-04,0,0,0
1470,review,1NarMOcLeTcMY8TOUew_zA,MibHji0QCYlLsewuqq4wwA,1,Been here a few times and had great service on...,2016-03-13,0,0,0
1473,review,4A628qyYpA4EhN6w6o-MYQ,GHCJTSnp1W9C9Zvdsz30Hw,1,After waiting 1.5 hrs we called to check on ou...,2016-03-26,0,1,0
1474,review,4A628qyYpA4EhN6w6o-MYQ,6aiOCOdLv-cWt6M4ce6kFg,1,This review comes a bit late but two Sunday's ...,2016-04-30,0,0,0
1475,review,eZblSTFIjpqPtDawFi3UXQ,6aiOCOdLv-cWt6M4ce6kFg,1,"Just sat down for breakfast, after 6 minutes a...",2014-12-11,0,0,1
1478,review,4A628qyYpA4EhN6w6o-MYQ,zuA84UZg4QiB1iBJNHkp9Q,1,We just moved to Scottsdale and were looking t...,2016-05-03,0,0,1
1479,review,4A628qyYpA4EhN6w6o-MYQ,ReKEZ0Mjvf62U7h4Z0K0Ew,1,Vary bad customer service for delivery. Order ...,2016-05-31,0,0,0
1480,review,94KtCPGHtHv9_u63vaFUHg,ReKEZ0Mjvf62U7h4Z0K0Ew,1,Lived here for a year. Looks cool from the out...,2015-01-04,0,6,0
1481,review,4A628qyYpA4EhN6w6o-MYQ,KQn6J_qSmSNMSTq6NENmfg,1,Worst service ever pizza never arrived. Don't ...,2016-06-06,0,0,0
1482,review,4A628qyYpA4EhN6w6o-MYQ,HTho1aIIykajFXFv7QyIPA,1,"Just got some pizza take out for dinner, nothi...",2016-06-23,0,0,0
1487,review,JsanjIgKkl_b6kc4qWC55Q,OvIs2hPhBl8TCUSYPB_EFQ,4,I love Indian food! And I've had a lot of Indi...,2009-03-01,0,2,0
1491,review,-4A5xmN21zi_TXnUESauUQ,w7oyRlhc6q0GGyUCbpDkcA,5,Delicious food. A little pricey for the type o...,2009-05-28,0,0,0
1492,review,hwXFp8FKJ7ivQb8_f4X23g,w7oyRlhc6q0GGyUCbpDkcA,5,Love this place. Anybody who throws up any of ...,2009-05-28,0,1,1
1493,review,SMpL3z4FLF07bRA6-y22JQ,mpuzmN0sz1eZLZ0XAMC2Dw,1,"After a 2 year absence, I was so excited to ha...",2010-02-24,0,0,0
1494,review,SMpL3z4FLF07bRA6-y22JQ,P-aJkgjwtKyjo54_rwm8iw,1,The first time we went to Malee's was really n...,2010-05-03,0,0,0
1495,review,SMpL3z4FLF07bRA6-y22JQ,6cy5oMq7bC1UdouvzFIdbQ,2,I went to Melee a couple of years ago and real...,2010-06-09,0,0,1
1497,review,SMpL3z4FLF07bRA6-y22JQ,xHBg0zMBCtTN39rzXjMeTA,5,"This is, hands down, the best Thai place in Sc...",2010-06-27,0,1,0
1498,review,SMpL3z4FLF07bRA6-y22JQ,N-GQu7N2XuDma6Gn5AmMKA,3,After being in Scottsdale for a couple days an...,2010-08-23,0,0,0
1499,review,dcd3C1gWv-vVdQ9XYV8Ubw,N-GQu7N2XuDma6Gn5AmMKA,3,The restaurant had a very welcoming feel to it...,2010-08-23,0,0,0

# GROUPBY!!!!

In [0]:
grouped_reviews = df.groupby('business_id')

In [0]:
grouped_reviews.head()

,type,business_id,user_id,stars,text,date,cool_votes,useful_votes,funny_votes
0,review,mxrXVZWc6PWk81gvOVNOUw,mv7shusL4Xb6TylVYBv4CA,4,Definitely try the duck dish. I rank it amon...,2011-06-13,0,0,0
1,review,mxrXVZWc6PWk81gvOVNOUw,0aN5QPhs-VwK2vusKG0waQ,5,Big Ass Burger was awesome! Great $5 mojitos. ...,2011-06-25,1,0,0
2,review,kK4AzZ0YWI-U2G-paAL7Fg,0aN5QPhs-VwK2vusKG0waQ,5,Unbelievable sandwiches! Good service.,2011-06-25,0,0,0
3,review,mxrXVZWc6PWk81gvOVNOUw,1JUwyYab-uJzEx_FRd81Zg,5,"Awesome, awesome, awesome! My mom and sister a...",2011-07-18,1,1,0
4,review,mxrXVZWc6PWk81gvOVNOUw,2Zd3Xy8hUVmZkNg7RyNjhg,4,I had the ribs they were great. The beer sele...,2011-07-19,1,0,1
5,review,iDYzGVIF1TDWdjHNgNjCVw,2Zd3Xy8hUVmZkNg7RyNjhg,4,"Great food, great drink. I had the crab enchil...",2011-07-19,0,0,0
6,review,dsMvINhoQbIQgSRTBv2B6g,2Zd3Xy8hUVmZkNg7RyNjhg,3,The only thing keeping this 5 stars is the pri...,2012-10-07,0,2,0
7,review,ZXRcWs5SUCvSfb8I2aLOnA,2Zd3Xy8hUVmZkNg7RyNjhg,4,My wife and I have been to many different Spas...,2010-08-24,0,0,0
8,review,YQvg0JCGRFUkb6reMMf3Iw,2Zd3Xy8hUVmZkNg7RyNjhg,4,This place in my mind is Postinos meets Bianco...,2011-07-11,1,1,0
9,review,GGVcdnKoRXldVEgergSF-A,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good lunch place. Everything I have had is be...,2012-11-17,0,0,0
10,review,1Q_H3BLhKBymF6Se8FfZNw,2Zd3Xy8hUVmZkNg7RyNjhg,3,When you look at the price you pay you expect ...,2010-08-24,0,0,0
11,review,YKOvlBNkF4KpUP9q7x862w,2Zd3Xy8hUVmZkNg7RyNjhg,3,"Very nice restaurant, great food, great servic...",2015-08-24,0,0,0
12,review,YYy3aQoLvjLhXPkpB32uzA,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food and service are OK. I will go back. ...,2014-04-22,0,0,0
13,review,xY1sPHTA2RGVFlh5tZhs9g,2Zd3Xy8hUVmZkNg7RyNjhg,2,I went here with Friends. All my friends and I...,2011-06-28,1,2,0
14,review,sjCRI-lCh4KLO_RYQdlEeQ,2Zd3Xy8hUVmZkNg7RyNjhg,1,I went here with Friends last Friday. All my ...,2011-06-27,0,5,1
15,review,nMHhuYan8e3cONo3PornJA,2Zd3Xy8hUVmZkNg7RyNjhg,5,"This is a unique, awesome place with a cool me...",2011-07-19,0,0,0
16,review,_WP0nIqmrSFLcY8nV8KUSA,2Zd3Xy8hUVmZkNg7RyNjhg,4,This place is very nice date restaurant. They...,2012-11-25,1,1,1
17,review,jtzhY-P4H6WSYpv5rWhxtw,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food was great the service was bad. If th...,2014-04-22,0,1,0
18,review,Cr2JNnewX53TYd9w6qw6Jw,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good burger good value.,2011-07-26,0,1,0
19,review,GDmue1oJaem9ilywDtA4_A,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was great. The service was so-so. A...,2013-02-14,0,0,0
20,review,JjLy3f1LyaE9ayRK18XQRg,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was very good. Great flavor not just...,2016-02-11,0,0,0
21,review,mxrXVZWc6PWk81gvOVNOUw,fuGfZWfDFf97d6UyuO3d8w,4,I was in Scottsdale on business and this was a...,2011-09-27,0,0,0
22,review,E7nk0lC317pGxMX56gvaVQ,fuGfZWfDFf97d6UyuO3d8w,2,First off to call yourself a bar and not serve...,2011-09-27,0,2,0
23,review,66jI6z-JuLasvd692ymycg,fuGfZWfDFf97d6UyuO3d8w,1,If Toby Keith is affiliated with this place in...,2013-11-13,1,10,2
24,review,IwShjaQLAvqV2msU4bh3ww,fuGfZWfDFf97d6UyuO3d8w,5,"This place is a Gem! It's small, dont get me w...",2013-11-28,0,0,0
26,review,UKgSs_SJzW9fu4CwhIV1yA,ghvcceMVfgukJMVsi9A1bA,5,The only thing that comes to my mind is why ar...,2011-10-02,0,1,0
27,review,On_3zLdujQdvDbBYUirNWw,ghvcceMVfgukJMVsi9A1bA,3,Service was 4 stars but we're here for the foo...,2011-10-02,0,0,0
28,review,OE5nAmaSVaopeRS1Cs9Kuw,ghvcceMVfgukJMVsi9A1bA,3,LISTEN CLOSELY FELLOW YELPERS.....\n\nTHIS 3 S...,2011-10-02,0,0,0
30,review,b78Cnqgeb4GoHqPobBXsjw,66aU_4HfubG5wJ3ZPR29og,5,I was visiting Scottsdale and staying at a nea...,2011-10-28,1,1,0
32,review,Q4ULAiIE2qCA4RYplCTrUQ,fRxsxrX71_qMpeF2MFJcYw,1,Ferguson joined me on a business trip here and...,2013-05-11,0,5,0
...,...,...,...,...,...,...,...,...,...
546983,review,CDPMn7Ypo8ZI7KXIDZ8Kyg,2mAYL4gK9vXvcBEE_BeLgQ,5,Best Greek restaurant in town!! We've been to ...,2014-01-30,1,1,0
546984,review,cyibZ2ijuDshKHlQs4IB5w,2mAYL4gK9vXvcBEE_BeLgQ,4,Nil bleu was a good experience. Food is a bit ...,2014-03-02,0,0,0
546985,review,xrPzf2fsktXjpOh1UgynbQ,2mAYL4gK9vXvcBEE_BeLgQ,4,This is the first sushi restaurant to open in ...,2014-01-09,0,2,0
546986,review,G65-1ikYzfa2EQO0NCJgXw,2mAYL4gK9vXvcBEE_BeLgQ,4,Had supper for the first time at Punjab Palace...,2014-02-26,0,1,0
546987,review,9JaXk_9PPJVgmf0-_TEozA,2mAYL4gK9vXvcBEE_BeLgQ,4,Breakfast on weekends are one of the best! The...,2015-03-07,0,1,0
546988,review,1nYhyiluPnAGssHin3dU1g,2mAYL4gK9vXvcBEE_BeLgQ,4,Hidden gem in TMR! This place if very good for...,2015-11-26,0,0,0
546989,review,jWg5J2MRjhp1kgXTY8pSOw,2mAYL4gK9vXvcBEE_BeLgQ,4,Blanche neige is knowned for their 2$ breakfas...,2014-02-26,2,3,0
546990,review,adcwt4WMpPnQNhtS7z60dQ,2mAYL4gK9vXvcBEE_BeLgQ,1,Lily is very good at what she does..unfortunat...,2014-12-05,0,1,0
546991,review,k8Lwi5ovd9Z-7W_OKRs-ag,2mAYL4gK9vXvcBEE_BeLgQ,5,This little lebanese cuisine restaurant is a t...,2014-01-04,0,0,0
546992,review,0-0vwg9IWq3QtKUzEpM1RQ,2mAYL4gK9vXvcBEE_BeLgQ,5,Looking for a treat? You found the perfect loc...,2015-05-02,0,0,0
546993,review,--AKjxBmhm9DWrh-e0hTOw,2mAYL4gK9vXvcBEE_BeLgQ,5,Had supper at Grigio last night for the first ...,2014-03-02,0,0,0
546994,review,uNkfoYfsm-sDfWRWNqXqew,2mAYL4gK9vXvcBEE_BeLgQ,4,I am surprised by the bad reviews! I've been d...,2014-03-02,0,1,0
546995,review,Rqw2y4YX4F2x5sbnzSbT6Q,2mAYL4gK9vXvcBEE_BeLgQ,3,Used to be my favourite spot for years. I was ...,2014-02-26,0,1,0
546998,review,GNTvJtw1gDFr92PMpq_sEw,2mAYL4gK9vXvcBEE_BeLgQ,4,"For steak lovers, this is a good place to go t...",2014-01-09,1,1,1
546999,review,jO8IWN5imZJ5Nq5qPLqgFQ,2mAYL4gK9vXvcBEE_BeLgQ,4,This restaurant is a Gem!! Located in St-Miche...,2015-11-26,0,0,0
547000,review,2tR2plCqVfYA_FBrYD88jQ,2mAYL4gK9vXvcBEE_BeLgQ,5,Ami & her team are professionals! I've been do...,2015-06-24,0,0,0
547001,review,TOuU0mn8cgDXOv_BB1VE3Q,2mAYL4gK9vXvcBEE_BeLgQ,5,"Love, love, love Kazumi! I've been going since...",2014-01-09,3,3,1
547002,review,MyUKlPfmbuiDvsVua38xRQ,2mAYL4gK9vXvcBEE_BeLgQ,4,Breakfast at Tiffany's..well what can I say? I...,2014-02-26,0,0,0
547003,review,3R-_XyZDvyCc9UMAHZHUWA,2mAYL4gK9vXvcBEE_BeLgQ,4,Family run business are always the best. This ...,2015-05-02,2,3,0
547004,review,hpSoja-1NNrdDLOFScZeHA,2mAYL4gK9vXvcBEE_BeLgQ,5,Amigo! The best place in Chinatown since Van R...,2014-02-26,0,2,0
547005,review,3ReIdkMJl9A_W74YioWBqg,2mAYL4gK9vXvcBEE_BeLgQ,5,Thank you Azig for my perfect eyebrows! She is...,2016-01-11,1,1,0
547006,review,X6iURwT-GB1WzjpUb38hWg,2mAYL4gK9vXvcBEE_BeLgQ,5,"Best Pho in Montreal!! Family owned business, ...",2014-01-04,1,1,0
547007,review,E7aMofC6KrCw3cFIcza30g,2mAYL4gK9vXvcBEE_BeLgQ,5,This restaurant has been opened since forever....,2014-03-05,0,2,0
547008,review,clXWPRAlZ9DFYHcEdI-ukg,2mAYL4gK9vXvcBEE_BeLgQ,5,The best Indian restaurant in Montreal! Family...,2015-11-26,0,0,0
547017,review,cOuf4T33pbwejU6BxqtVzQ,GL-wwCnzwdbbh-xN_sVZ8w,5,Best tour guides! I've been lucky to have take...,2016-05-24,0,0,0
547023,review,_JgDJsioF0mSzO4uVmwuSQ,pnY52Ox7U5QPUYb5HqFWxw,5,When I say this place is top notch boy it is t...,2015-07-16,0,0,0
547076,review,HPH-wa5z2_pBKqv1CDf8Ag,puuknpRR1LnUbmJcmcAbGA,1,"The ""lounge"" is pretty bad, if I could I would...",2013-11-11,0,0,0
547087,review,1sodGyqul2SB_EEGynM9hw,dlbXw6Xg8eseHstKjf8sYA,5,Contacted them at 4:42 PM on a Saturday and a ...,2015-09-05,0,2,0
547176,review,ol9qP41LTuW9YXNhDeWqrA,1v9DI2t18_Llp18QSpvp6w,1,It took four months to sell our house. You nev...,2016-05-03,0,0,0
547188,review,wCsS6Ar28DGhKKD11O41Tw,eCowZZiT1fl92oN-1lkfWA,5,Walked in today to get a small bouquet of flow...,2016-06-16,0,0,0

In [0]:
grouped_reviews = df.groupby('business_id').mean()

#grouped_reviews = df.groupby('business_id').count()

In [0]:
grouped_reviews.head()

                           stars  cool_votes  useful_votes  funny_votes
business_id
--5jkZ3-nUPZxUvtcbr8Uw  4.680000        0.16      0.120000         0.12
--AKjxBmhm9DWrh-e0hTOw  5.000000        0.00      0.000000         0.00
--BlvDO_RG2yElKu9XA1_g  4.600000        0.10      0.300000         0.10
--Ol5mVSMaW8ExtmWRUmKA  5.000000        0.00      1.000000         0.00
--Y_2lDOtVDioX5bwF6GIw  2.666667        0.00      0.666667         0.00

#### Performing operations on columns

In [0]:
df['new_stars'] = 2*df['stars']

#### Use of numpy

In [0]:
import numpy as np

df['new_column'] = np.mean(df['cool_votes'])

In [0]:
df

,type,business_id,user_id,stars,text,date,cool_votes,useful_votes,funny_votes,new_stars,new_column
0,review,mxrXVZWc6PWk81gvOVNOUw,mv7shusL4Xb6TylVYBv4CA,4,Definitely try the duck dish. I rank it amon...,2011-06-13,0,0,0,8,0.389438
1,review,mxrXVZWc6PWk81gvOVNOUw,0aN5QPhs-VwK2vusKG0waQ,5,Big Ass Burger was awesome! Great $5 mojitos. ...,2011-06-25,1,0,0,10,0.389438
2,review,kK4AzZ0YWI-U2G-paAL7Fg,0aN5QPhs-VwK2vusKG0waQ,5,Unbelievable sandwiches! Good service.,2011-06-25,0,0,0,10,0.389438
3,review,mxrXVZWc6PWk81gvOVNOUw,1JUwyYab-uJzEx_FRd81Zg,5,"Awesome, awesome, awesome! My mom and sister a...",2011-07-18,1,1,0,10,0.389438
4,review,mxrXVZWc6PWk81gvOVNOUw,2Zd3Xy8hUVmZkNg7RyNjhg,4,I had the ribs they were great. The beer sele...,2011-07-19,1,0,1,8,0.389438
5,review,iDYzGVIF1TDWdjHNgNjCVw,2Zd3Xy8hUVmZkNg7RyNjhg,4,"Great food, great drink. I had the crab enchil...",2011-07-19,0,0,0,8,0.389438
6,review,dsMvINhoQbIQgSRTBv2B6g,2Zd3Xy8hUVmZkNg7RyNjhg,3,The only thing keeping this 5 stars is the pri...,2012-10-07,0,2,0,6,0.389438
7,review,ZXRcWs5SUCvSfb8I2aLOnA,2Zd3Xy8hUVmZkNg7RyNjhg,4,My wife and I have been to many different Spas...,2010-08-24,0,0,0,8,0.389438
8,review,YQvg0JCGRFUkb6reMMf3Iw,2Zd3Xy8hUVmZkNg7RyNjhg,4,This place in my mind is Postinos meets Bianco...,2011-07-11,1,1,0,8,0.389438
9,review,GGVcdnKoRXldVEgergSF-A,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good lunch place. Everything I have had is be...,2012-11-17,0,0,0,8,0.389438
10,review,1Q_H3BLhKBymF6Se8FfZNw,2Zd3Xy8hUVmZkNg7RyNjhg,3,When you look at the price you pay you expect ...,2010-08-24,0,0,0,6,0.389438
11,review,YKOvlBNkF4KpUP9q7x862w,2Zd3Xy8hUVmZkNg7RyNjhg,3,"Very nice restaurant, great food, great servic...",2015-08-24,0,0,0,6,0.389438
12,review,YYy3aQoLvjLhXPkpB32uzA,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food and service are OK. I will go back. ...,2014-04-22,0,0,0,6,0.389438
13,review,xY1sPHTA2RGVFlh5tZhs9g,2Zd3Xy8hUVmZkNg7RyNjhg,2,I went here with Friends. All my friends and I...,2011-06-28,1,2,0,4,0.389438
14,review,sjCRI-lCh4KLO_RYQdlEeQ,2Zd3Xy8hUVmZkNg7RyNjhg,1,I went here with Friends last Friday. All my ...,2011-06-27,0,5,1,2,0.389438
15,review,nMHhuYan8e3cONo3PornJA,2Zd3Xy8hUVmZkNg7RyNjhg,5,"This is a unique, awesome place with a cool me...",2011-07-19,0,0,0,10,0.389438
16,review,_WP0nIqmrSFLcY8nV8KUSA,2Zd3Xy8hUVmZkNg7RyNjhg,4,This place is very nice date restaurant. They...,2012-11-25,1,1,1,8,0.389438
17,review,jtzhY-P4H6WSYpv5rWhxtw,2Zd3Xy8hUVmZkNg7RyNjhg,3,The food was great the service was bad. If th...,2014-04-22,0,1,0,6,0.389438
18,review,Cr2JNnewX53TYd9w6qw6Jw,2Zd3Xy8hUVmZkNg7RyNjhg,4,Good burger good value.,2011-07-26,0,1,0,8,0.389438
19,review,GDmue1oJaem9ilywDtA4_A,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was great. The service was so-so. A...,2013-02-14,0,0,0,8,0.389438
20,review,JjLy3f1LyaE9ayRK18XQRg,2Zd3Xy8hUVmZkNg7RyNjhg,4,The food was very good. Great flavor not just...,2016-02-11,0,0,0,8,0.389438
21,review,mxrXVZWc6PWk81gvOVNOUw,fuGfZWfDFf97d6UyuO3d8w,4,I was in Scottsdale on business and this was a...,2011-09-27,0,0,0,8,0.389438
22,review,E7nk0lC317pGxMX56gvaVQ,fuGfZWfDFf97d6UyuO3d8w,2,First off to call yourself a bar and not serve...,2011-09-27,0,2,0,4,0.389438
23,review,66jI6z-JuLasvd692ymycg,fuGfZWfDFf97d6UyuO3d8w,1,If Toby Keith is affiliated with this place in...,2013-11-13,1,10,2,2,0.389438
24,review,IwShjaQLAvqV2msU4bh3ww,fuGfZWfDFf97d6UyuO3d8w,5,"This place is a Gem! It's small, dont get me w...",2013-11-28,0,0,0,10,0.389438
25,review,mxrXVZWc6PWk81gvOVNOUw,ghvcceMVfgukJMVsi9A1bA,4,Fresh Baked Bread to start!\nGreat Tortilla So...,2011-10-02,0,1,0,8,0.389438
26,review,UKgSs_SJzW9fu4CwhIV1yA,ghvcceMVfgukJMVsi9A1bA,5,The only thing that comes to my mind is why ar...,2011-10-02,0,1,0,10,0.389438
27,review,On_3zLdujQdvDbBYUirNWw,ghvcceMVfgukJMVsi9A1bA,3,Service was 4 stars but we're here for the foo...,2011-10-02,0,0,0,6,0.389438
28,review,OE5nAmaSVaopeRS1Cs9Kuw,ghvcceMVfgukJMVsi9A1bA,3,LISTEN CLOSELY FELLOW YELPERS.....\n\nTHIS 3 S...,2011-10-02,0,0,0,6,0.389438
29,review,mxrXVZWc6PWk81gvOVNOUw,66aU_4HfubG5wJ3ZPR29og,4,"My friends wanted to eat ""Southwest cuisine,"" ...",2011-10-28,0,0,0,8,0.389438
...,...,...,...,...,...,...,...,...,...,...,...
547243,review,uJYw4p59AKh8c8h5yWMdOw,uoZfwWjyZ2WwZh5mZDavSg,3,I actually really liked this hotel. I got a st...,2016-06-21,1,1,2,6,0.389438
547244,review,uJYw4p59AKh8c8h5yWMdOw,bbjBSYN07Om6OCmL-f_fpQ,1,"Awful place, expensive for the things they giv...",2016-06-21,0,0,0,2,0.389438
547245,review,uJYw4p59AKh8c8h5yWMdOw,3pA7EQTv-hJmdWdQjVmNAg,1,Slowest checkin on the Planet. Plan on 1 yo 1 ...,2016-06-21,0,0,0,2,0.389438
547246,review,XG7izXBfvxrZNtjgQWA8tA,3pA7EQTv-hJmdWdQjVmNAg,1,Been in a Sky Priority line for 45 mins. Defin...,2016-06-23,0,0,0,2,0.389438
547247,review,uJYw4p59AKh8c8h5yWMdOw,PHuODesPB9t_RT9NuGVJWA,5,It was our first time staying here and we will...,2016-06-21,0,0,0,10,0.389438
547248,review,uJYw4p59AKh8c8h5yWMdOw,Muqs5VhklzOvEQgEHYbDkw,1,Absolutely the worst place you can stay in Las...,2016-06-23,0,0,1,2,0.389438
547249,review,Nw8lWJRGybAsciao9h-R2Q,Muqs5VhklzOvEQgEHYbDkw,5,Its really impossible to dislike this place. T...,2016-03-03,0,0,0,10,0.389438
547250,review,sih8j621A66QoiUFues5qQ,Muqs5VhklzOvEQgEHYbDkw,1,"I love Downtown Las Vegas, I live Downtown. I ...",2016-03-03,0,0,0,2,0.389438
547251,review,o3AVHzQR-q8yx3inBelvXA,Muqs5VhklzOvEQgEHYbDkw,5,Now that this place is run by the people from ...,2016-06-23,0,0,0,10,0.389438
547252,review,u5bGaiZGosBf-L9lYLCg5g,Muqs5VhklzOvEQgEHYbDkw,5,Just great! I am such a fan. I love management...,2016-06-23,0,0,0,10,0.389438
547253,review,uJYw4p59AKh8c8h5yWMdOw,Q6jZOJKSvbzcLFebk_NIaQ,3,Stayed here in May since we were seeing JLO at...,2016-06-23,0,1,0,6,0.389438
547254,review,uJYw4p59AKh8c8h5yWMdOw,9ylE8m-hEm3lwboPnIb-tA,5,My family and I just had another great stay th...,2016-06-27,0,0,0,10,0.389438
547255,review,65_YeaivbdWNk1ZHiAI77w,9ylE8m-hEm3lwboPnIb-tA,1,Ate here last night with my family and first i...,2016-06-27,0,0,0,2,0.389438
547256,review,sIyHTizqAiGu12XMLX3N3g,9ylE8m-hEm3lwboPnIb-tA,5,Definitely a must for buffet on the strip!! As...,2016-06-27,0,0,0,10,0.389438
547257,review,uJYw4p59AKh8c8h5yWMdOw,NQdPrQenFgHdvU_TQR75Mg,1,"Last weekend, I went to Las Vegas for my bache...",2016-06-28,0,0,0,2,0.389438
547258,review,uJYw4p59AKh8c8h5yWMdOw,jliMC5OzQigkLPl-lKh65Q,3,First time in Vegas and we got a great deal. F...,2016-06-30,0,0,0,6,0.389438
547259,review,QbmcCE_cLq4WO8ZMKImaLw,jliMC5OzQigkLPl-lKh65Q,5,I ordered the Chicken and waffles. Chicken was...,2016-06-30,0,0,0,10,0.389438
547260,review,uJYw4p59AKh8c8h5yWMdOw,Cm4bdEnwVp-dpYTt5b2OaA,4,We had a really nice time staying at planet Ho...,2016-07-01,0,0,0,8,0.389438
547261,review,uJYw4p59AKh8c8h5yWMdOw,k8JyU5xQl4L7w1Sp01YugQ,4,I always seem to stay at Planet Hollywood when...,2016-07-03,0,0,0,8,0.389438
547262,review,zt1TpTuJ6y9n551sw9TaEg,k8JyU5xQl4L7w1Sp01YugQ,4,I've been to this buffet a few times now and e...,2016-07-03,0,1,0,8,0.389438
547263,review,nrtQ1MbahiNDSRn5CyA-Sw,k8JyU5xQl4L7w1Sp01YugQ,4,The Chandelier is one of those fancy schmancy ...,2016-07-03,0,0,0,8,0.389438
547264,review,aGbjLWzcrnEx2ZmMCFm3EA,k8JyU5xQl4L7w1Sp01YugQ,4,I love BurGR. I make it a point to always eat ...,2016-07-03,0,1,0,8,0.389438
547265,review,QhwkFogGQA-Ar176Ul5PUQ,k8JyU5xQl4L7w1Sp01YugQ,3,Although I'm a Cali girl and I'm supposed to b...,2016-07-03,1,0,0,6,0.389438
547266,review,VPzETgEJPY0ekHyiCRcqLg,k8JyU5xQl4L7w1Sp01YugQ,4,The boyfriend and I were heading to Fashion Sh...,2016-07-03,1,3,1,8,0.389438
547267,review,uJYw4p59AKh8c8h5yWMdOw,duDHzrsxPCkvScdie495Og,1,My fiance and myself stayed here July 3rd to t...,2016-07-04,0,0,0,2,0.389438
547268,review,uJYw4p59AKh8c8h5yWMdOw,RbfDvjqqzzqT-ipvWWyPTg,2,Non smoking hotel room reeked of smoking.\nCar...,2016-07-06,0,1,0,4,0.389438
547269,review,uJYw4p59AKh8c8h5yWMdOw,2K6zSLJy-zxLB7sqONfGvQ,3,Great location right on the strip but I defini...,2016-07-08,0,1,1,6,0.389438
547270,review,9CLZ-Uwv3nmOlbbGCIhvrQ,2K6zSLJy-zxLB7sqONfGvQ,3,If you're staying in Planet Hollywood and look...,2016-07-08,0,1,0,6,0.389438
547271,review,aGbjLWzcrnEx2ZmMCFm3EA,2K6zSLJy-zxLB7sqONfGvQ,4,I'm not a huge burger person but got dragged i...,2016-07-08,1,0,0,8,0.389438
547272,review,JhfNoSE1DA0tPr3R1MwE8w,2K6zSLJy-zxLB7sqONfGvQ,5,The best meal I've had in Vegas so far! Try th...,2016-07-06,0,0,0,10,0.389438